openapi: 3.0.1


info:
  version: 1.0.0
  title: 'Web practice API'
  description: 'Desc'
  license: 
    name: ''
    url: 's'
    

servers:
  - url: http://127.0.0.1:8000/api
    description: 'Local server'


paths:
  /auth/login:
    $ref: "./paths/login.yaml#/paths/loginRoute"
       
  /books:
    get:
      description: 'get books list'
      parameters: 
        - in: query
          name: offset
          description: 'offset of the records starts from 0'
          schema:
            type: integer
            example: 50   
        - in: query
          name: limit
          description: 'limit of the records 1 - 100'
          schema:
            type: integer
            example: 50   
      tags: 
        -  Books
      responses: 
        200: 
          description: 'Success'
          content: 
            application/json: 
              schema: 
                properties: 
                  books:
                    type: array
                    items: 
                      type: object
                      properties: 
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'Consequatur mollitia voluptatem eos ipsum'
                        authors:
                          type: array
                          items: 
                            type: object
                            properties: 
                              id:
                                type: integer
                                example: 5
                              name:
                                type: string
                                example: 'Clark Parker'
                        publisher:
                          type: object
                          properties: 
                            id:
                              type: integer
                              example: 10
                            name:
                              type: string
                              example: 'Fisherfort'
      

  # /books/{id}:
  #   $ref: ./paths/getBookInfo.yaml#/paths/getBookInfo   
    
  # /books/{ido}:
  #   $ref: ./paths/createBook.yaml#/paths/createBook

  # /books/book:
  #   $ref: "./paths/updateBook.yaml#/paths/updateBook"

  # /books/books:
  #   $ref: "./paths/deleteBook.yaml#/paths/deleteBook"


components:
  headers:
    Api-Token:
      description: 'JWT токен'
      schema:
        type: string
        example: "hsiOGFUD8&T867T786t"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
